services:
  publisher:
    build: .
    command: uv run uvicorn publisher.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      RABBITMQ_HOST: rabbitmq
      REDIS_HOST: redis
    networks:
      - shared_net
    depends_on:
      - jaeger

  consumer:
    build: .
    command: uv run python -m consumer.worker
    environment:
      RABBITMQ_HOST: rabbitmq
      REDIS_HOST: redis
    networks:
      - shared_net
    depends_on:
      - jaeger

  llm_worker:
    build: .
    command: uv run python -m llm_worker.worker
    environment:
      RABBITMQ_HOST: rabbitmq
    networks:
      - shared_net
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
    networks:
      - shared_net

networks:
  shared_net:
    external: true
    name: shared_net